import type { Metadata } from "next";
import "@/app/globals.css";
import SideBar from "@/components/SideBar";


export const metadata: Metadata = {
  title: "FocusFlo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="flex">
        <SideBar />
        <main className="flex-1 p-4">{children}</main>
      </body>
    </html>
  );
}
