import type { Metadata } from "next";
import "@/app/globals.css";


export const metadata: Metadata = {
  title: "FocusFlo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
